### PR TITLE
bump nytlabels-annotator packages

### PR DESCRIPTION
**Pull request by jtotoole**
fixes https://github.com/mediacloud/backend/issues/748

(i couldn't push directly to `master` for permissions reasons)

### CODE REVIEW

**Comment by pypt** [comment]
> (i couldn't push directly to master for permissions reasons)

Weird, what kind of an error do you get?

**Comment by pypt** [comment]
Also, did you try running it and verify that the HTTP server works and responds with annotations?

**Comment by jtotoole** [comment]
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
To https://github.com/mediacloud/backend.git
 ! [remote rejected]     master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/mediacloud/backend.git'
```

I ran the tests for `nytlabels-fetch-annotation` + `nytlabels-update-story-tags`, which both worked—was that the right approach re: HTTP server?

**Comment by pypt** [comment]
Fixed.

**Pull request closed without merging**
