### PR TITLE
[WIP] Remove Crimson Hexagon references

### PR DESCRIPTION
**Pull request by jtotoole**
Now that we've deprecated Crimson Hexagon in favor of Brandwatch, per @dsjen, this code can go. 

@pypt Do we need to add `select insert_platform_source_pair( 'twitter', 'brandwatch' );` [here](https://github.com/mediacloud/backend/blob/master/apps/postgresql-server/schema/mediawords.sql#L1859-L1864) in `mediawords.sql`? If so i can do that in a separate PR.

### CODE REVIEW

**Comment by jtotoole** [comment]
I’ll check on these test failures tomorrow

**Comment by pypt** [comment]
Thanks for the initiative!

(Get the system monitoring working first though :))

**Comment by pypt** [comment]
What's left here:

* [ ] Remove `apps/topics-mine/src/perl/MediaWords/Config/TopicsMine.pm` and references to it (if any);
* [ ] Remove imports of `topics_mine.config`;
* [ ] It looks like there's a mapping between `brandwatch` source and `twitter` platform in production (but not in code, as is tradition :)), so yeah, we probably need that `insert_platform_source_pair()` call;
* [ ] Tiny typo in `doc/dev_scripts.markdown` (extra `-e`)

Otherwise great work!

**Comment by pypt** [comment]
(I took the liberty to merge in recent changes from `master` to your branch.)

**Pull request closed without merging**
